import io.gitlab.arturbosch.detekt.Detekt

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '2.0.10'
    ext.detekt_version = '1.21.0'

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath libs.gradle
        classpath libs.kotlin.gradle.plugin
        classpath libs.kotlin.serialization
        classpath libs.apollo.gradle.plugin
        classpath libs.detekt.gradle.plugin
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlinx.serialization) apply false
    alias(libs.plugins.apollo3) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.compose.compiler) apply false

//    id("io.gitlab.arturbosch.detekt") version "1.21.0"
    // todo replace with version catalog (throws error)
//    alias(libs.plugins.detekt) apply false
}

subprojects {
//    detekt {
//        config = files("$projectDir/config/detekt.yml")
//        baseline = file("$projectDir/config/baseline.xml")
//    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

tasks.withType(Detekt).configureEach {
    jvmTarget = "11"
}

tasks.withType(Detekt).configureEach {
    reports {
        html.required.set(true) // observe findings in your browser with structure and code snippets
        xml.required.set(true) // checkstyle like format mainly for integrations like Jenkins
    }
}
